NOT_FOUND = "Data Not found"
SUCCESS = "Success"
CREATED = "Created successfully"
UPDATED = "Updated successfully"
DELETED = "Deleted successfully"
DATA_FETCHED = "Data fetched successfully"
USER_LOGIN_SUCCESS = "User logged in successfully"
USER_LOGOUT_SUCCESS = "User logged out successfully"
REGISTRATION_SUCCESS = "Registration successful"
PASSWORD_RESET = "Password reset successfully"
TOKEN_FETCHED_SUCCESSFULLY = "Token fetched successfully."
PUBLISHED = "Published successfully."
INVALID_DATA = "Invalid data"
INVALID_CREDENTIAL = "Invalid credentials"

